---
permalink: sm-storage/delete-snapshot-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, delete, snapshot, volume 
summary: Snapshotボリューム、またはSnapshot整合性グループのSnapshotボリュームは、バックアップやソフトウェアアプリケーションのテストに必要なくなったときは削除することができます。 
---
= Snapshotボリュームを削除します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snapshotボリューム、またはSnapshot整合性グループのSnapshotボリュームは、バックアップやソフトウェアアプリケーションのテストに必要なくなったときは削除することができます。

関連付けられているSnapshotリザーブ容量ボリュームを削除するかどうかを指定することもできます。 `read-write` Snapshotボリュームを作成するか、またはSnapshotリザーブ容量ボリュームを未割り当てボリュームとして保持します。

.このタスクについて
ベースボリュームを削除すると、関連付けられているSnapshotボリュームまたは整合性グループのSnapshotボリュームは自動的に削除されます。ステータスが「実行中」のボリュームコピーの対象になっているSnapshotボリュームは削除できません。

.手順
. メニューを選択します。Storage [Snapshots]。
. スナップショットボリューム*タブを選択します。
+
System Managerに、ストレージアレイに関連付けられているすべてのSnapshotボリュームが表示されます。

. 削除するSnapshotボリュームを選択し、メニューから「一般的でないタスク」「削除」を選択します。
. 処理を実行することを確認し、* Delete *をクリックします。


.結果
System Managerは次の処理を実行します。

* メンバーであるSnapshotボリュームをすべて削除します（Snapshot整合性グループのSnapshotボリュームの場合）。
* 関連付けられているホスト割り当てをすべて削除します。

